[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pathgenevocam"
authors = [{name = "ajv37", email = "ajv37@cam.ac.uk"}]
dynamic = ["version", "description"]
